version: '3.9'
services:
  mongodb:
    container_name: greenthumb-mongodb
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017

  redis:
    container_name: greenthumb-redis
    image: redis:6
    restart: unless-stopped
    ports:
      - 6379:6379

  zookeeper:
    container_name: greenthumb-zookeeper
    image: confluentinc/cp-zookeeper:7.2.0
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      
  kafka:
    container_name: greenthumb-kafka
    image: confluentinc/cp-kafka:7.2.0
    restart: unless-stopped
    ports:
      - 9092:9092
    expose:
      - 29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://0.0.0.0:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
  init-kafka:
    image: confluentinc/cp-kafka:7.2.0
    depends_on:
      - kafka
    entrypoint: ["/setup.sh"]
    volumes:
      - ./setup/kafka.sh:/setup.sh

  cassandra:
    container_name: greenthumb-cassandra
    image: cassandra:4
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: greenthumb_cluster
  init-cassandra:
    image: cassandra:4
    depends_on:
      - cassandra
    entrypoint: ["/setup.sh"]
    volumes:
      - ./setup/cassandra.sh:/setup.sh

networks:
  default:
    name: greenthumb