#!/bin/bash

CYAN='\033[0;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

function greentext() {
  echo -e "${GREEN}${1}${NC}"
}

function yellowtext() {
  echo -e "${YELLOW}${1}${NC}"
}

function redtext() {
  echo -e "${RED}${1}${NC}"
}

function cyantext() {
  echo -e "${CYAN}${1}${NC}"
}

